version: '3.3'
services:

  foodgram-db:
    image: postgres:13.0-alpine
    volumes:
      - data_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  foodgram-backend:
    image: valiok123456/foodgram-backend:latest
    expose:
      - 8000
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    depends_on:
      - foodgram-db
    env_file:
      - ./.env

#  foodgram-frontend:
#   build:
#     context: ../frontend
#     dockerfile: Dockerfile
#   volumes:
#     - ../frontend/:/app/result_build/

  foodgram-nginx:
    image: valiok123456/foodgram-nginx:latest
      #image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    restart: always
#    depends_on:
#      - foodgram-frontend

volumes:
  data_value:
  static_value:
  media_value:
